# Generated by Django 5.2.3 on 2025-07-03 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driver",
            old_name="licence_number",
            new_name="license_number",
        ),
    ]
